###S3CopyBatch_KerimDorukAKINCI
SET ACCOUNTNAME=YOUR_ACCOUNT_NAME
SET AWS_ACCESS_KEY_ID=XXXXXXXXXXXXXXXXXXXXXXXXX
SET AWS_SECRET_ACCESS_KEY=XXXXXXXXXXXXXXXXXXXXXXXX
SET SOURCE_BUCKETNAME=bucketname.cloudformation
SET SOURCE_REGION=eu-west-1
SET TARGET_REGION=us-west-1
aws s3 cp s3://%SOURCE_BUCKETNAME% E:/CloudformationBackups/%ACCOUNTNAME%/%date:~-4,4%-%date:~-7,2%-%date:~-10,2% --source-region %SOURCE_REGION% --recursive --region %TARGET_REGION%
###